# Generated by Django 5.2.6 on 2025-12-01 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('effect_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filter_name', models.CharField(max_length=100)),
                ('filter_details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_name', models.CharField(max_length=100, unique=True)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('caption', models.TextField(blank=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.appuser')),
                ('post_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.posttype')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('comment_replied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='feed.comment')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.appuser')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_file', models.FileField(upload_to='media/')),
                ('position', models.IntegerField()),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.filter')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.FloatField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.effect')),
                ('post_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.postmedia')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='feed.appuser')),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='feed.appuser')),
            ],
            options={
                'unique_together': {('following_user', 'followed_user')},
            },
        ),
        migrations.CreateModel(
            name='PostMediaUserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('post_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.postmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.appuser')),
            ],
            options={
                'unique_together': {('post_media', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.appuser')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
